# Render deployment configuration for TrashApp Backend
services:
  - type: web
    name: trashapp-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Required environment variables (set these in Render dashboard)
    # - key: MONGO_URI
    #   sync: false
    # - key: JWT_SECRET
    #   sync: false
    # - key: JWT_EXPIRE
    #   value: 1h
    # - key: FRONTEND_URL
    #   sync: false
